region_country = dict(
    South_West_Europe=[
        "Italy",
        "Spain",
        "Portugal",
        "Canary Islands",
        "Cyprus",
        "Turkey",
        "Malta",
        "Toscani",
    ],
    Central_Europe=[
        "France",
        "Poland",
        "Ireland",
        "Germany",
        "Netherlands",
        "UK",
        "Switzerland",
        "Luxembourg",
        "Austria",
        "Slovakia",
        "CEPH",
        "Belgium",
        "Monaco",
        "Czechoslovakia",
        "Czech Republic",
        "Orkney Islands",
        "Great Britain",
    ],
    South_East_Europe=[
        "Montenegro",
        "Greece",
        "Albania",
        "Croatia",
        "Ukraine",
        "Armenia",
        "Slovenia",
        "Romania",
        "Moldova",
        "Azerbaijan",
        "Hungary",
        "Georgia",
        "Bulgaria",
        "Serbia",
        "Moldova",
        "Bulgaria",
        "Barbados",
        "Abkhazia",
        "Macedonia",
        "Belarus",
        "Serbia",
    ],
    North_East_Europe=[
        "Sweden",
        "Denmark",
        "Estonia",
        "Norway",
        "Iceland",
        "Lithuania",
        "Latvia",
        "Finland",
        "Greenland",
    ],
    South_America=[
        "Belize",
        "Argentina",
        "Honduras",
        "Esan,Esan",
        "Esan",
        "Peru",
        "Venezuela",
        "Barbados",
        "Brazil",
        "Chile",
        "Uruguay",
        "Jamaica",
        "Puerto Rico",
        "Bahamas",
        "Panama",
        "Bolivia",
        "Mexico",
        "Colombia",
        "Ecuador",
        "El Salvador",
        "Bolivia",
    ],
    Africa=[
        "South Africa",
        "Kenya",
        "Gambian Mandinka,Gambian",
        "Yemen",
        "Eritrea",
        "Luhya",
        "Luhya,Luhya",
        "Gambia",
        "Lesotho",
        "Libya",
        "Lesotho",
        "Yoruba",
        "Malawi",
        "Sudan",
        "Mende",
        "Mende,Mende",
        "Sierra Leone",
        "Western Sahara (Morocco)",
        "Samoa",
        "Cameroon",
        "Botswana",
        "BotswanaOrNamibia",
        "Namibia",
        "Morocco",
        "SouthAfrica",
        "Congo",
        "Eswatini",
        "Ethiopia",
        "Nigeria",
        "Tanzania",
        "Angola",
        "Tunisia",
        "Algeria",
        "Senegal",
        "Bengali",
        "Egypt",
        "Gambian Mandinka",
        "Central African Republic",
    ],
    South_Asia=[
        "India",
        "Brunei",
        "Gujarati",
        "Myanmar",
        "Punjabi",
        "Punjabi,Punjabi",
        "Thailand",
        "Philippines",
        "Laos",
        "Sri Lanka",
        "Singapore",
        "Malaysia",
        "Cambodia",
        "South Korea",
        "Bengali,Bengali",
        "Bangladesh",
        "Vietnam",
        "KinhVietnamese",
        "Kinh,Kinh Vietnamese",
        "Kinh Vietnamese",
        "SriLanka",
        "Nepal",
        "Taiwan",
        "SouthKorea",
    ],
    North_Asia=[
        "Russia",
        "China",
        "Japan",
        "Tajikistan",
        "Mongolia",
        "Turkmenistan",
        "Kazakhstan",
        "Uzbekistan",
        "Kyrgyzstan",
    ],
    West_Asia=[
        "Pakistan",
        "Iraq",
        "Jordan",
        "Israel",
        "Saudi Arabia",
        "Syria",
        "Iran",
        "Lebanon",
    ],
    Oceania=[
        "New Zealand",
        "Indonesia",
        "Papua New Guinea",
        "Australia",
        "Samoa",
        "Tonga",
        "Solomon Islands",
        "Vanuatu",
        "French Polynesia",
        "Micronesia",
    ],
    North_America=["USA", "Canada"],
)

country_region = {}
for key, values in region_country.items():
    for val in values:
        country_region[val] = key.replace('_', ' ')
